unit test stage

diff --git a/docker-files/unit_test b/docker-files/unit_test
--- a/docker-files/unit_test
+++ b/docker-files/unit_test
@@ -1,7 +1,14 @@
 #!/bin/sh
 
-set -o errexit
-set -o pipefail
-set -o nounset
+set -e
+trap 'catch $? $LINENO' EXIT
+
+catch() {
+  echo "catching!"
+  if [ "$1" != "0" ]; then
+    # error handling goes here
+    echo "Error $1 occurred on $2"
+  fi
+}
 
 python -m pytest library/tests
